language: python

branches:
  only:
  - master

# # only build on tags
# if: tag IS present

env:
  global:
    - PACKER_VERSION="1.2.2"

before_install:
 - sudo apt-get update -y --fix-missing

install:
 # Install Packer.io
 - packer --version
 - curl -o /tmp/packer.zip -L "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
 - sudo unzip -d /usr/local/packer-${PACKER_VERSION} /tmp/packer.zip
 - sudo ln -sf /usr/local/packer-${PACKER_VERSION}/packer /usr/local/bin/packer
 - packer --version

script:
  - echo "Running build script on tag $TRAVIS_TAG"
  - ./build-ami.sh $TRAVIS_TAG


notifications:
  email: false
    # recipients:
    #   - florian.reisinger@unimelb.edu.au
    # on_failure: always
    # on_success: always
  slack: false
