AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Notifies that a VCF sample is ready to be processed
Resources:
  triggerPCGR:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: Notifies that a VCF sample is ready to be processed
      MemorySize: 128
      Timeout: 5
      Role: 'arn:aws:iam::620123204273:role/service-role/sqs_s3_lambda'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '-germline.tar.gz'
        BucketEvent2:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket2
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '-somatic.tar.gz'
        BucketEvent3:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket3
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '-normal.tar.gz'
      Tags:
        'lambda_related_service': pcgr
        service: arteria
  Bucket1:
    Type: 'AWS::S3::Bucket'
  Bucket2:
    Type: 'AWS::S3::Bucket'
  Bucket3:
    Type: 'AWS::S3::Bucket'
